In [1]:
import numpy as np
np.random.seed(42)
import sys
import cProfile
import humanize
# import imp
# import logging
# imp.reload(logging)
# logging.basicConfig(level=logging.DEBUG)
sys.path.insert(0, '../..')
%reload_ext memory_profiler
%reload_ext autoreload
%autoreload 1
%aimport allel.model
%aimport allel.stats.diversity
%aimport allel.stats
%aimport allel.plot
%aimport allel.opt.stats

In [8]:
g = [[[0, 0], [0, 0], [1, 1], [1, 1]],
     [[0, 1], [0, 1], [0, 1], [0, 1]],
     [[0, 0], [0, 0], [0, 0], [0, 0]],
     [[0, 1], [1, 2], [1, 1], [2, 2]],
     [[0, 0], [1, 1], [0, 1], [-1, -1]]]
subpops = [[0, 1], [2, 3]]
g = allel.model.GenotypeArray(g)
ac1 = g.count_alleles(subpop=subpops[0])
ac2 = g.count_alleles(subpop=subpops[1])

In [3]:
a, b, c = allel.stats.weir_cockerham_anova(g, subpops)
a[:, 1], b[:, 1], c[:, 1]

(array([ 0.5  ,  0.   ,  0.   , -0.125, -0.375]),
 array([ 0.        , -0.25      ,  0.        ,  0.125     ,  0.41666667]),
 array([ 0.        ,  0.5       ,  0.        ,  0.25      ,  0.16666667]))

In [4]:
a[:, 1] / (a[:, 1] + b[:, 1] + c[:, 1])

array([ 1. ,  0. ,  nan, -0.5, -1.8])

In [5]:
a[:, 2] / (a[:, 2] + b[:, 2] + c[:, 2])

array([ nan,  nan,  nan, -0.5,  nan])

In [6]:
np.sum(a, axis=1) / (np.sum(a, axis=1) + np.sum(b, axis=1) + np.sum(c, axis=1))

array([ 1. ,  0. ,  nan, -0.4, -1.8])

In [11]:
num, den = allel.stats.hudson_fst(ac1, ac2)
num, den

(array([ 1.        , -0.16666667,  0.        , -0.125     , -0.33333333]),
 array([ 1.   ,  0.5  ,  0.   ,  0.625,  0.5  ]))

In [12]:
num / den

array([ 1.        , -0.33333333,         nan, -0.2       , -0.66666667])

In [18]:
g2 = [[[0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [1, 1], [1, 1], [1, 1]],
     [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]],
     [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]],
     [[0, 1], [1, 2], [0, 1], [1, 2], [1, 1], [2, 2], [1, 1], [2, 2]],
     [[0, 0], [1, 1], [0, 0], [1, 1], [0, 1], [-1, -1], [0, 1], [-1, -1]]]
subpops2 = [[0, 1, 2, 3], [4, 5, 6, 7]]
g2 = allel.model.GenotypeArray(g2)
ac21 = g2.count_alleles(subpop=subpops2[0])
ac22 = g2.count_alleles(subpop=subpops2[1])

In [19]:
a, b, c = allel.stats.weir_cockerham_anova(g2, subpops2)
a[:, 1], b[:, 1], c[:, 1]

(array([ 0.5       ,  0.        ,  0.        , -0.04166667, -0.09375   ]),
 array([ 0.        , -0.25      ,  0.        ,  0.04166667,  0.16666667]),
 array([ 0.        ,  0.5       ,  0.        ,  0.25      ,  0.16666667]))

In [20]:
a[:, 1] / (a[:, 1] + b[:, 1] + c[:, 1])

array([ 1.        ,  0.        ,         nan, -0.16666667, -0.39130435])

In [21]:
num, den = allel.stats.hudson_fst(ac21, ac22)
num, den

(array([ 1.        , -0.07142857,  0.        , -0.01785714, -0.11904762]),
 array([ 1.   ,  0.5  ,  0.   ,  0.625,  0.5  ]))

In [22]:
num / den

array([ 1.        , -0.14285714,         nan, -0.02857143, -0.23809524])

In [24]:
g3 = [[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [1, 1], [1, 1], [1, 1]],
     [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]],
     [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]],
     [[0, 1], [1, 2], [0, 1], [1, 2], [0, 1], [1, 2], [0, 1], [1, 2], [1, 1], [2, 2], [1, 1], [2, 2]],
     [[0, 0], [1, 1], [0, 0], [1, 1], [0, 0], [1, 1], [0, 0], [1, 1], [0, 1], [-1, -1], [0, 1], [-1, -1]]]
subpops3 = [list(range(8)), list(range(8, 12))]
g3 = allel.model.GenotypeArray(g3)
ac31 = g3.count_alleles(subpop=subpops3[0])
ac32 = g3.count_alleles(subpop=subpops3[1])

In [25]:
a, b, c = allel.stats.weir_cockerham_anova(g3, subpops3)
a[:, 1], b[:, 1], c[:, 1]

(array([ 0.5     ,  0.      ,  0.      , -0.01875 , -0.078125]),
 array([ 0.        , -0.25      ,  0.        , -0.06666667,  0.2       ]),
 array([ 0.        ,  0.5       ,  0.        ,  0.33333333,  0.1       ]))

In [26]:
a[:, 1] / (a[:, 1] + b[:, 1] + c[:, 1])

array([ 1.        ,  0.        ,         nan, -0.07563025, -0.35211268])

In [27]:
num, den = allel.stats.hudson_fst(ac31, ac32)
num, den

(array([ 1.        , -0.05238095,  0.        ,  0.00595238, -0.1       ]),
 array([ 1.   ,  0.5  ,  0.   ,  0.625,  0.5  ]))

In [28]:
num / den

array([ 1.        , -0.1047619 ,         nan,  0.00952381, -0.2       ])

In [29]:
# setup an array of genotype calls
shape = n_variants, n_samples, ploidy = 50000, 1000, 2
data = np.zeros(shape, dtype='i1')
# simulate some mutations
n_alleles = n_variants * n_samples * ploidy
idx = np.random.randint(0, (n_alleles//2)-1, size=n_alleles//20)
data[:, :, 1].reshape((-1))[idx] = 1
data[:, :, 0].reshape((-1))[idx[:n_alleles//200]] = 1

In [30]:
g = allel.model.GenotypeArray(data, copy=False)
g

GenotypeArray((50000, 1000, 2), dtype=int8)
[[[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 1]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 ..., 
 [[0 0]
  [0 1]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 1]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]]

In [31]:
subpops = [np.arange(0, 500), np.arange(500, 1000)]

In [32]:
a, b, c = allel.stats.weir_cockerham_anova(g, subpops)

In [33]:
fst = a[:, 0] / (a[:, 0] + b[:, 0] + c[:, 0])
fst

array([ -8.83881584e-04,   8.18538485e-04,  -1.09694980e-03, ...,
        -5.14830085e-04,   4.86184077e-05,  -2.62540045e-04])

In [34]:
fst = a[:, 1] / (a[:, 1] + b[:, 1] + c[:, 1])
fst

array([ -8.83881584e-04,   8.18538485e-04,  -1.09694980e-03, ...,
        -5.14830085e-04,   4.86184077e-05,  -2.62540045e-04])

In [35]:
ac1 = g.count_alleles(subpop=subpops[0])
ac2 = g.count_alleles(subpop=subpops[1])
num, den = allel.stats.hudson_fst(ac1, ac2)
num / den

array([ -6.95817769e-04,   9.87003824e-04,  -9.58854478e-04, ...,
        -3.38898428e-04,   2.19173920e-04,  -8.53563906e-05])

In [23]:
%timeit allel.stats.weir_cockerham_anova(g, subpops)
%memit allel.stats.weir_cockerham_anova(g, subpops)

1 loops, best of 3: 811 ms per loop


In [36]:
%timeit allel.stats.hudson_fst(ac1, ac2)
%memit allel.stats.hudson_fst(ac1, ac2)

100 loops, best of 3: 6.33 ms per loop
peak memory: 213.39 MiB, increment: 0.14 MiB


In [25]:
gc = allel.bcolz.GenotypeCArray(data)
gc

GenotypeCArray((50000, 1000, 2), int8)
  nbytes: 95.37 MB; cbytes: 15.97 MB; ratio: 5.97
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[[[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 1]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 ..., 
 [[0 0]
  [0 1]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 1]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]]

In [26]:
%timeit allel.stats.weir_cockerham_anova(gc, subpops)

1 loops, best of 3: 1.44 s per loop


In [27]:
%memit allel.stats.weir_cockerham_anova(gc, subpops)

peak memory: 227.23 MiB, increment: 3.14 MiB


In [28]:
ac, bc, cc = allel.stats.weir_cockerham_anova(gc, subpops)

In [29]:
np.array_equal(a, ac)

True

In [30]:
np.array_equal(b, bc)

True

In [31]:
np.array_equal(c, cc)

True