In [1]:
import sys
sys.path.insert(0, '../..')
from allel.io_vcf_read import read_vcf, _read_vcf
from allel.opt.io_vcf_read import (iter_vcf, 
#                                    CalldataParser_parse, 
#                                    GenotypeInt8Parser_parse, 
#                                    ParserContext_next, 
#                                    BufferedReader_read
                                  )

In [2]:
prof_vcf_fn = '/localssd/kwiat/vector/ag1000g/release/phase1.AR3.1/haplotypes/specific_regions/PARA/2L_2358158_2431617.vcf.gz'
sample_vcf_fn = '../../fixture/sample.vcf'

In [3]:
results = read_vcf(sample_vcf_fn, buffer_size=2**15, block_size=3)

In [4]:
sorted(results[0].keys())

['calldata/GT',
 'variants/ALT',
 'variants/CHROM',
 'variants/FILTER',
 'variants/ID',
 'variants/POS',
 'variants/QUAL',
 'variants/REF']

In [5]:
results[0]['variants/CHROM']

array([b'19', b'19', b'20'], 
      dtype='|S12')

In [6]:
results[0]['variants/POS']

array([  111,   112, 14370], dtype=int32)

In [7]:
results[0]['variants/ID']

array([b'.', b'.', b'rs6054257'], 
      dtype='|S12')

In [8]:
results[0]['variants/REF']

array([b'A', b'A', b'G'], 
      dtype='|S1')

In [9]:
results[0]['variants/ALT']

array([[b'C', b'', b''],
       [b'G', b'', b''],
       [b'A', b'', b'']], 
      dtype='|S1')

In [10]:
results[0]['variants/QUAL']

array([  9.60000038,  10.        ,  29.        ], dtype=float32)

In [11]:
results[0]['variants/FILTER']

array([[False],
       [False],
       [ True]], dtype=bool)

In [12]:
results[0]['calldata/GT']

array([[[0, 0],
        [0, 0],
        [0, 1]],

       [[0, 0],
        [0, 0],
        [0, 1]],

       [[0, 0],
        [1, 0],
        [1, 1]]], dtype=int8)

In [13]:
results = read_vcf(prof_vcf_fn, buffer_size=2**15, block_size=1000)

In [14]:
len(results)

2

In [15]:
sorted(results[0].keys())

['calldata/GT',
 'variants/ALT',
 'variants/CHROM',
 'variants/FILTER',
 'variants/ID',
 'variants/POS',
 'variants/QUAL',
 'variants/REF']

In [16]:
results[0]['calldata/GT'].shape

(1000, 773, 2)

In [17]:
results[1]['calldata/GT'].shape

(968, 773, 2)

In [18]:
results[0]['variants/CHROM']

array([b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L', b'2L',
       b'2L', b'2L',

In [19]:
results[0]['variants/POS']

array([2353212, 2353223, 2353234, 2353251, 2353288, 2353294, 2353299,
       2353319, 2353321, 2353359, 2353363, 2353387, 2353460, 2353470,
       2353507, 2353514, 2353525, 2353579, 2353583, 2353635, 2353650,
       2354069, 2354231, 2354449, 2354494, 2354502, 2354508, 2354526,
       2354536, 2354539, 2354756, 2355009, 2355078, 2356461, 2356464,
       2356481, 2356487, 2356491, 2356492, 2356495, 2356665, 2356738,
       2356745, 2356788, 2357178, 2357179, 2357186, 2357218, 2357221,
       2357262, 2357321, 2357532, 2357537, 2357544, 2357556, 2357577,
       2357610, 2357646, 2357726, 2357768, 2357784, 2357816, 2357825,
       2357828, 2357833, 2357837, 2357850, 2357859, 2357860, 2357862,
       2357867, 2357873, 2357915, 2357955, 2357991, 2357993, 2357997,
       2358007, 2358036, 2358056, 2358063, 2358084, 2358093, 2358254,
       2358316, 2358328, 2358353, 2358405, 2358621, 2358667, 2358707,
       2358734, 2358747, 2358801, 2358808, 2358818, 2358853, 2358884,
       2359201, 2359

In [20]:
results[0]['variants/REF']

array([b'G', b'T', b'G', b'A', b'G', b'T', b'A', b'C', b'C', b'A', b'T',
       b'G', b'C', b'G', b'C', b'C', b'C', b'A', b'T', b'C', b'T', b'C',
       b'A', b'G', b'T', b'T', b'A', b'G', b'A', b'T', b'A', b'A', b'T',
       b'C', b'A', b'C', b'C', b'A', b'C', b'C', b'A', b'A', b'T', b'A',
       b'G', b'A', b'A', b'C', b'C', b'C', b'T', b'A', b'C', b'A', b'G',
       b'G', b'A', b'C', b'C', b'T', b'C', b'A', b'C', b'C', b'T', b'A',
       b'A', b'C', b'T', b'C', b'C', b'A', b'A', b'A', b'G', b'C', b'G',
       b'C', b'T', b'G', b'T', b'T', b'G', b'G', b'T', b'T', b'C', b'T',
       b'G', b'T', b'T', b'C', b'T', b'T', b'G', b'T', b'A', b'T', b'T',
       b'C', b'C', b'T', b'T', b'C', b'T', b'C', b'G', b'G', b'T', b'T',
       b'G', b'C', b'A', b'A', b'T', b'T', b'A', b'G', b'C', b'T', b'T',
       b'A', b'A', b'T', b'G', b'C', b'A', b'A', b'G', b'G', b'A', b'T',
       b'C', b'T', b'T', b'A', b'T', b'T', b'C', b'T', b'G', b'C', b'G',
       b'A', b'A', b'T', b'A', b'G', b'T', b'C', b'

In [21]:
results[0]['variants/ALT']

array([[b'A', b'', b''],
       [b'G', b'', b''],
       [b'C', b'', b''],
       ..., 
       [b'C', b'', b''],
       [b'G', b'', b''],
       [b'A', b'', b'']], 
      dtype='|S1')

In [22]:
%time _ = read_vcf(prof_vcf_fn, buffer_size=2**15, block_size=1000)

CPU times: user 132 ms, sys: 0 ns, total: 132 ms
Wall time: 133 ms


In [23]:
%timeit _ = read_vcf(prof_vcf_fn, buffer_size=2**15, block_size=1000)

10 loops, best of 3: 92.1 ms per loop


In [24]:
import cProfile

In [25]:
cProfile.run('read_vcf(prof_vcf_fn, buffer_size=2**15, block_size=1000)', sort='time')

         46560 function calls (46176 primitive calls) in 0.148 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.072    0.072    0.111    0.111 {allel.opt.io_vcf_read.iter_vcf}
      377    0.021    0.000    0.021    0.000 {method 'decompress' of 'zlib.Decompress' objects}
     7744    0.011    0.000    0.066    0.000 gzip.py:269(read)
8128/7744    0.011    0.000    0.048    0.000 {method 'read' of '_io.BufferedReader' objects}
      473    0.009    0.000    0.009    0.000 {built-in method zlib.crc32}
       12    0.007    0.001    0.036    0.003 io_vcf_read.py:45(_binary_readline)
     7744    0.005    0.000    0.007    0.000 _compression.py:12(_check_not_closed)
     7746    0.002    0.000    0.002    0.000 gzip.py:296(closed)
      378    0.002    0.000    0.036    0.000 gzip.py:436(read)
      378    0.002    0.000    0.037    0.000 _compression.py:66(readinto)
      949    0.001    0.000    0.002    0.000 

In [37]:
import line_profiler
l = line_profiler.LineProfiler()
# l.add_function(_read_vcf)
l.add_function(iter_vcf)
l.add_function(CalldataParser_parse)
l.add_function(GenotypeInt8Parser_parse)
# l.add_function(ParserContext_next)
# l.add_function(BufferedReader_read)
l.runcall(read_vcf, prof_vcf_fn, buffer_size=2**15, block_size=1000)
l.print_stats()

Timer unit: 1e-06 s

Total time: 27.5659 s
File: ../../allel/io_vcf_read.py
Function: _read_vcf at line 38

Line #      Hits         Time  Per Hit   % Time  Line Contents
    38                                           def _read_vcf(fileobj, buffer_size, block_size, temp_max_size):
    39         1        24608  24608.0      0.1      headers, samples = _read_vcf_headers(fileobj)
    40                                               # debug(samples)
    41         1            2      2.0      0.0      return iter_vcf(fileobj, buffer_size=buffer_size, block_size=block_size,
    42         1     27541339 27541339.0     99.9                      temp_max_size=temp_max_size, n_samples=len(samples))

Total time: 27.4744 s
File: /home/aliman/src/github/cggh/scikit-allel/allel/opt/io_vcf_read.pyx
Function: iter_vcf at line 34

Line #      Hits         Time  Per Hit   % Time  Line Contents
    34                                           def iter_vcf(binary_file, buffer_size, block_size, n_samp

In [26]:
import vcfnp

In [28]:
%time vcfnp.calldata(prof_vcf_fn, fields=('genotype',))

[vcfnp] 2017-05-24 14:49:30.651145 :: caching is disabled
[vcfnp] 2017-05-24 14:49:30.651788 :: building array


CPU times: user 4.31 s, sys: 0 ns, total: 4.31 s
Wall time: 4.3 s


array([ (([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), (

In [29]:
4.3 / 0.09

47.77777777777778

## Legacy

In [ ]:
vcf_block_read(vcf_fn, buffer_size=2**15, block_size=2**25)

In [3]:
%time spike_read_len(vcf_fn, buffer_size=10)

CPU times: user 700 ms, sys: 0 ns, total: 700 ms
Wall time: 697 ms


6140661

In [4]:
%timeit spike_read_len(vcf_fn, buffer_size=100)

10 loops, best of 3: 105 ms per loop


In [5]:
%timeit spike_read_len(vcf_fn, buffer_size=1000)

10 loops, best of 3: 50 ms per loop


In [6]:
%timeit spike_read_len(vcf_fn, buffer_size=2**15)

10 loops, best of 3: 39 ms per loop


In [7]:
%timeit spike_read_len(vcf_fn, buffer_size=2**12)

10 loops, best of 3: 45.3 ms per loop


In [8]:
import cProfile

In [9]:
cProfile.run('spike_read_len(vcf_fn, buffer_size=2**15)', sort='time')

         6146762 function calls (6146566 primitive calls) in 0.941 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.584    0.584    0.941    0.941 io_vcf.pyx:90(spike_read_len)
  6140662    0.322    0.000    0.356    0.000 io_vcf.pyx:74(BufferedInputStream_next)
      189    0.019    0.000    0.019    0.000 {method 'decompress' of 'zlib.Decompress' objects}
      285    0.008    0.000    0.008    0.000 {built-in method zlib.crc32}
  385/189    0.001    0.000    0.033    0.000 {method 'read' of '_io.BufferedReader' objects}
      190    0.001    0.000    0.031    0.000 gzip.py:436(read)
      190    0.001    0.000    0.033    0.000 _compression.py:66(readinto)
      761    0.001    0.000    0.001    0.000 gzip.py:80(read)
      189    0.001    0.000    0.034    0.000 gzip.py:269(read)
      189    0.000    0.000    0.035    0.000 io_vcf.pyx:56(BufferedInputStream_fill_buffer)
       97    0.000    0.000    0.00

In [10]:
import line_profiler

l = line_profiler.LineProfiler()
l.add_function(spike_read_len)
l.add_function(BufferedInputStream_next)
l.add_function(BufferedInputStream_fill_buffer)
l.runcall(spike_read_len, vcf_fn, buffer_size=2**14)
l.print_stats()

## Legacy

In [ ]:
l = line_profiler.CLineProfiler

In [3]:
2**15

32768

In [ ]:
blocks = io_vcf.vcf_block_read(vcf_fn, buffer_size=2**16, block_size=1000)

HeaderParser_parse 37873392 35
20
b'##fileformat=VCFv4.1'
HeaderParser_parse 37873413 35
60
b'##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">'
HeaderParser_parse 37873474 35
124
b'##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele countin genotypes, for each ALT allele, in the same order aslisted">'
HeaderParser_parse 37873599 35
32
b'##contig=<ID=2L,length=49364325>'
HeaderParser_parse 37873632 35
32
b'##contig=<ID=2R,length=61545105>'
HeaderParser_parse 37873665 35
32
b'##contig=<ID=3L,length=41963435>'
HeaderParser_parse 37873698 35
32
b'##contig=<ID=3R,length=53200684>'
HeaderParser_parse 37873731 35
34
b'##contig=<ID=UNKN,length=42389979>'
HeaderParser_parse 37873766 35
31
b'##contig=<ID=X,length=24393108>'
HeaderParser_parse 37873798 35
38
b'##contig=<ID=Y_unplaced,length=237045>'
HeaderParser_parse 37873837 35
106
b'##reference=file:///data/anopheles/ag1000g/data/genome/AgamP3/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP3.fa'
HeaderParser_parse 37873944 35
7002
