In [1]:
import sys
sys.path.insert(0, '../..')
from allel.io_vcf_read import read_vcf, read_vcf_chunks, vcf_to_npz, vcf_to_hdf5
from allel.opt.io_vcf_read import (iter_vcf, 
#                                    CalldataParser_parse, 
#                                    GenotypeInt8Parser_parse, 
#                                    ParserContext_next, 
#                                    BufferedReader_read
                                  )

In [2]:
prof_vcf_fn = '/localssd/kwiat/vector/ag1000g/release/phase1.AR3.1/haplotypes/specific_regions/PARA/2L_2358158_2431617.vcf.gz'
sample_vcf_fn = '../../fixture/sample.vcf'

In [3]:
samples, chunks = read_vcf_chunks(sample_vcf_fn, buffer_size=2**15, chunk_length=3)
samples

[b'NA00001', b'NA00002', b'NA00003']

In [4]:
chunks = list(chunks)
len(chunks)

3

In [5]:
sorted(chunks[0].keys())

['calldata/GT',
 'variants/ALT',
 'variants/CHROM',
 'variants/FILTER',
 'variants/ID',
 'variants/POS',
 'variants/QUAL',
 'variants/REF']

In [6]:
sum([r['variants/CHROM'].shape[0] for r in chunks])

9

In [7]:
chunks[0]['variants/CHROM']

array([b'19', b'19', b'20'], 
      dtype='|S12')

In [8]:
chunks[-1]['variants/CHROM']

array([b'20', b'20', b'X'], 
      dtype='|S12')

In [9]:
chunks[0]['variants/POS']

array([  111,   112, 14370], dtype=int32)

In [10]:
chunks[-1]['variants/POS']

array([1234567, 1235237,      10], dtype=int32)

In [11]:
chunks[0]['variants/ID']

array([b'.', b'.', b'rs6054257'], 
      dtype='|S12')

In [12]:
chunks[0]['variants/REF']

array([b'A', b'A', b'G'], 
      dtype='|S1')

In [13]:
chunks[0]['variants/ALT']

array([[b'C', b'', b''],
       [b'G', b'', b''],
       [b'A', b'', b'']], 
      dtype='|S1')

In [14]:
chunks[0]['variants/QUAL']

array([  9.60000038,  10.        ,  29.        ], dtype=float32)

In [15]:
chunks[0]['variants/FILTER']

array([[False],
       [False],
       [ True]], dtype=bool)

In [16]:
chunks[0]['calldata/GT']

array([[[0, 0],
        [0, 0],
        [0, 1]],

       [[0, 0],
        [0, 0],
        [0, 1]],

       [[0, 0],
        [1, 0],
        [1, 1]]], dtype=int8)

In [17]:
callset = read_vcf(prof_vcf_fn, buffer_size=2**15, chunk_length=1000)

In [18]:
sorted(callset.keys())

['calldata/GT',
 'samples',
 'variants/ALT',
 'variants/CHROM',
 'variants/FILTER',
 'variants/ID',
 'variants/POS',
 'variants/QUAL',
 'variants/REF']

In [19]:
callset['samples']

array([b'AB0085-C', b'AB0087-C', b'AB0088-C', b'AB0089-C', b'AB0090-C',
       b'AB0091-C', b'AB0092-C', b'AB0094-C', b'AB0095-C', b'AB0097-C',
       b'AB0098-C', b'AB0099-C', b'AB0100-C', b'AB0101-C', b'AB0103-C',
       b'AB0104-C', b'AB0109-C', b'AB0110-C', b'AB0111-C', b'AB0112-C',
       b'AB0113-C', b'AB0114-C', b'AB0117-C', b'AB0119-C', b'AB0122-C',
       b'AB0123-C', b'AB0124-C', b'AB0126-C', b'AB0127-C', b'AB0128-C',
       b'AB0129-C', b'AB0130-C', b'AB0133-C', b'AB0134-C', b'AB0135-C',
       b'AB0136-C', b'AB0137-C', b'AB0138-C', b'AB0139-C', b'AB0140-C',
       b'AB0142-C', b'AB0143-C', b'AB0145-C', b'AB0146-C', b'AB0147-C',
       b'AB0148-C', b'AB0151-C', b'AB0153-C', b'AB0155-C', b'AB0157-C',
       b'AB0158-C', b'AB0159-C', b'AB0160-C', b'AB0161-C', b'AB0164-C',
       b'AB0166-C', b'AB0169-C', b'AB0170-C', b'AB0171-C', b'AB0172-C',
       b'AB0173-C', b'AB0174-C', b'AB0175-C', b'AB0176-C', b'AB0177-C',
       b'AB0178-C', b'AB0179-C', b'AB0181-C', b'AB0182-C', b'AB0

In [20]:
callset['calldata/GT'].shape

(1967, 773, 2)

In [21]:
callset['calldata/GT'].shape

(1967, 773, 2)

In [22]:
callset['variants/CHROM']

array([b'2L', b'2L', b'2L', ..., b'2L', b'2L', b'2L'], 
      dtype='|S12')

In [23]:
callset['variants/POS']

array([2353212, 2353223, 2353234, ..., 2436558, 2436585, 2436615], dtype=int32)

In [24]:
callset['variants/REF']

array([b'G', b'T', b'G', ..., b'G', b'A', b'C'], 
      dtype='|S1')

In [25]:
callset['variants/ALT']

array([[b'A', b'', b''],
       [b'G', b'', b''],
       [b'C', b'', b''],
       ..., 
       [b'A', b'', b''],
       [b'C', b'', b''],
       [b'A', b'', b'']], 
      dtype='|S1')

## Format conversion

In [26]:
npz_fn = 'sample.npz'
vcf_to_npz(sample_vcf_fn, npz_fn, chunk_length=3, overwrite=False)

ValueError: file exists at path 'sample.npz'; use overwrite=True to replace

In [27]:
vcf_to_npz(sample_vcf_fn, npz_fn, chunk_length=3, overwrite=True)

In [28]:
!ls -lh {npz_fn}

-rw-r--r-- 1 aliman aliman 1.8K May 24 19:42 sample.npz


In [29]:
import numpy as np

In [30]:
callset = np.load(npz_fn)
callset

In [31]:
sorted(callset.keys())

['calldata/GT',
 'samples',
 'variants/ALT',
 'variants/CHROM',
 'variants/FILTER',
 'variants/ID',
 'variants/POS',
 'variants/QUAL',
 'variants/REF']

In [32]:
callset['samples']

array([b'NA00001', b'NA00002', b'NA00003'], 
      dtype='|S7')

In [33]:
callset['variants/POS']

array([    111,     112,   14370,   17330, 1110696, 1230237, 1234567,
       1235237,      10], dtype=int32)

In [34]:
callset['variants/CHROM']

array([b'19', b'19', b'20', b'20', b'20', b'20', b'20', b'20', b'X'], 
      dtype='|S12')

In [35]:
callset['calldata/GT']

array([[[ 0,  0],
        [ 0,  0],
        [ 0,  1]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  1]],

       [[ 0,  0],
        [ 1,  0],
        [ 1,  1]],

       [[ 0,  0],
        [ 0,  1],
        [ 0,  0]],

       [[ 1,  2],
        [ 2,  1],
        [ 2,  2]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  1],
        [ 0,  2],
        [-1, -1]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]],

       [[ 0, -1],
        [ 0,  1],
        [ 0,  2]]], dtype=int8)

In [36]:
hdf5_fn = 'sample.h5'
vcf_to_hdf5(sample_vcf_fn, hdf5_fn, chunk_length=3)

ValueError: dataset exists at path 'calldata/GT'; use overwrite=True to replace

In [37]:
vcf_to_hdf5(sample_vcf_fn, hdf5_fn, chunk_length=3, overwrite=True)

In [38]:
!ls -lh {hdf5_fn}

-rw-r--r-- 1 aliman aliman 33K May 24 19:42 sample.h5


In [39]:
!h5ls {hdf5_fn}

calldata                 Group
samples                  Dataset {3}
variants                 Group


In [40]:
!h5ls {hdf5_fn}/variants

ALT                      Dataset {9/Inf, 3}
CHROM                    Dataset {9/Inf}
FILTER                   Dataset {9/Inf, 1}
ID                       Dataset {9/Inf}
POS                      Dataset {9/Inf}
QUAL                     Dataset {9/Inf}
REF                      Dataset {9/Inf}


In [41]:
!h5ls {hdf5_fn}/variants/CHROM

CHROM                    Dataset {9/Inf}


In [42]:
!h5ls {hdf5_fn}/calldata

GT                       Dataset {9/Inf, 3, 2}


In [43]:
!h5ls {hdf5_fn}/calldata/GT

GT                       Dataset {9/Inf, 3, 2}


In [44]:
import h5py

In [45]:
with h5py.File(hdf5_fn, mode='r') as h5f:
    print(h5f['samples'][:])
    print(h5f['variants/CHROM'][:])
    print(h5f['variants/POS'][:])
    print(h5f['calldata/GT'][:])
    

[b'NA00001' b'NA00002' b'NA00003']
[b'19' b'19' b'20' b'20' b'20' b'20' b'20' b'20' b'X']
[    111     112   14370   17330 1110696 1230237 1234567 1235237      10]
[[[ 0  0]
  [ 0  0]
  [ 0  1]]

 [[ 0  0]
  [ 0  0]
  [ 0  1]]

 [[ 0  0]
  [ 1  0]
  [ 1  1]]

 [[ 0  0]
  [ 0  1]
  [ 0  0]]

 [[ 1  2]
  [ 2  1]
  [ 2  2]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[ 0  1]
  [ 0  2]
  [-1 -1]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]

 [[ 0 -1]
  [ 0  1]
  [ 0  2]]]


## Profiling

In [ ]:
%time _ = read_vcf(prof_vcf_fn, buffer_size=2**15, chunk_length=1000)

In [ ]:
%timeit _ = read_vcf(prof_vcf_fn, buffer_size=2**15, chunk_length=1000)

In [30]:
import cProfile

In [31]:
cProfile.run('read_vcf(prof_vcf_fn, buffer_size=2**15, chunk_length=1000)', sort='time')

         46579 function calls (46195 primitive calls) in 0.135 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.074    0.074    0.114    0.114 {allel.opt.io_vcf_read.iter_vcf}
      377    0.021    0.000    0.021    0.000 {method 'decompress' of 'zlib.Decompress' objects}
      473    0.009    0.000    0.009    0.000 {built-in method zlib.crc32}
8128/7744    0.007    0.000    0.045    0.000 {method 'read' of '_io.BufferedReader' objects}
     7744    0.006    0.000    0.055    0.000 gzip.py:269(read)
       12    0.004    0.000    0.019    0.002 io_vcf_read.py:222(_binary_readline)
     7744    0.003    0.000    0.004    0.000 _compression.py:12(_check_not_closed)
      378    0.002    0.000    0.037    0.000 gzip.py:436(read)
      378    0.002    0.000    0.039    0.000 _compression.py:66(readinto)
      949    0.002    0.000    0.002    0.000 gzip.py:80(read)
     7746    0.001    0.000    0.001    0.000 gz

In [37]:
import line_profiler
l = line_profiler.LineProfiler()
# l.add_function(_read_vcf)
l.add_function(iter_vcf)
l.add_function(CalldataParser_parse)
l.add_function(GenotypeInt8Parser_parse)
# l.add_function(ParserContext_next)
# l.add_function(BufferedReader_read)
l.runcall(read_vcf, prof_vcf_fn, buffer_size=2**15, block_size=1000)
l.print_stats()

Timer unit: 1e-06 s

Total time: 27.5659 s
File: ../../allel/io_vcf_read.py
Function: _read_vcf at line 38

Line #      Hits         Time  Per Hit   % Time  Line Contents
    38                                           def _read_vcf(fileobj, buffer_size, block_size, temp_max_size):
    39         1        24608  24608.0      0.1      headers, samples = _read_vcf_headers(fileobj)
    40                                               # debug(samples)
    41         1            2      2.0      0.0      return iter_vcf(fileobj, buffer_size=buffer_size, block_size=block_size,
    42         1     27541339 27541339.0     99.9                      temp_max_size=temp_max_size, n_samples=len(samples))

Total time: 27.4744 s
File: /home/aliman/src/github/cggh/scikit-allel/allel/opt/io_vcf_read.pyx
Function: iter_vcf at line 34

Line #      Hits         Time  Per Hit   % Time  Line Contents
    34                                           def iter_vcf(binary_file, buffer_size, block_size, n_samp

In [26]:
import vcfnp

In [28]:
%time vcfnp.calldata(prof_vcf_fn, fields=('genotype',))

[vcfnp] 2017-05-24 14:49:30.651145 :: caching is disabled
[vcfnp] 2017-05-24 14:49:30.651788 :: building array


CPU times: user 4.31 s, sys: 0 ns, total: 4.31 s
Wall time: 4.3 s


array([ (([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), ([0, 0],), (

In [29]:
4.3 / 0.09

47.77777777777778

## Legacy

In [ ]:
vcf_block_read(vcf_fn, buffer_size=2**15, block_size=2**25)

In [3]:
%time spike_read_len(vcf_fn, buffer_size=10)

CPU times: user 700 ms, sys: 0 ns, total: 700 ms
Wall time: 697 ms


6140661

In [4]:
%timeit spike_read_len(vcf_fn, buffer_size=100)

10 loops, best of 3: 105 ms per loop


In [5]:
%timeit spike_read_len(vcf_fn, buffer_size=1000)

10 loops, best of 3: 50 ms per loop


In [6]:
%timeit spike_read_len(vcf_fn, buffer_size=2**15)

10 loops, best of 3: 39 ms per loop


In [7]:
%timeit spike_read_len(vcf_fn, buffer_size=2**12)

10 loops, best of 3: 45.3 ms per loop


In [8]:
import cProfile

In [9]:
cProfile.run('spike_read_len(vcf_fn, buffer_size=2**15)', sort='time')

         6146762 function calls (6146566 primitive calls) in 0.941 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.584    0.584    0.941    0.941 io_vcf.pyx:90(spike_read_len)
  6140662    0.322    0.000    0.356    0.000 io_vcf.pyx:74(BufferedInputStream_next)
      189    0.019    0.000    0.019    0.000 {method 'decompress' of 'zlib.Decompress' objects}
      285    0.008    0.000    0.008    0.000 {built-in method zlib.crc32}
  385/189    0.001    0.000    0.033    0.000 {method 'read' of '_io.BufferedReader' objects}
      190    0.001    0.000    0.031    0.000 gzip.py:436(read)
      190    0.001    0.000    0.033    0.000 _compression.py:66(readinto)
      761    0.001    0.000    0.001    0.000 gzip.py:80(read)
      189    0.001    0.000    0.034    0.000 gzip.py:269(read)
      189    0.000    0.000    0.035    0.000 io_vcf.pyx:56(BufferedInputStream_fill_buffer)
       97    0.000    0.000    0.00

In [10]:
import line_profiler

l = line_profiler.LineProfiler()
l.add_function(spike_read_len)
l.add_function(BufferedInputStream_next)
l.add_function(BufferedInputStream_fill_buffer)
l.runcall(spike_read_len, vcf_fn, buffer_size=2**14)
l.print_stats()

## Legacy

In [ ]:
l = line_profiler.CLineProfiler

In [3]:
2**15

32768

In [ ]:
blocks = io_vcf.vcf_block_read(vcf_fn, buffer_size=2**16, block_size=1000)

HeaderParser_parse 37873392 35
20
b'##fileformat=VCFv4.1'
HeaderParser_parse 37873413 35
60
b'##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">'
HeaderParser_parse 37873474 35
124
b'##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele countin genotypes, for each ALT allele, in the same order aslisted">'
HeaderParser_parse 37873599 35
32
b'##contig=<ID=2L,length=49364325>'
HeaderParser_parse 37873632 35
32
b'##contig=<ID=2R,length=61545105>'
HeaderParser_parse 37873665 35
32
b'##contig=<ID=3L,length=41963435>'
HeaderParser_parse 37873698 35
32
b'##contig=<ID=3R,length=53200684>'
HeaderParser_parse 37873731 35
34
b'##contig=<ID=UNKN,length=42389979>'
HeaderParser_parse 37873766 35
31
b'##contig=<ID=X,length=24393108>'
HeaderParser_parse 37873798 35
38
b'##contig=<ID=Y_unplaced,length=237045>'
HeaderParser_parse 37873837 35
106
b'##reference=file:///data/anopheles/ag1000g/data/genome/AgamP3/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP3.fa'
HeaderParser_parse 37873944 35
7002
