In [1]:
import numpy as np
np.random.seed(42)
import sys
import cProfile
import humanize
import imp
import logging
imp.reload(logging)
logging.basicConfig(level=logging.DEBUG)
sys.path.insert(0, '../..')
%reload_ext memory_profiler
%reload_ext autoreload
%autoreload 1
%aimport allel.model
%aimport allel.stats.diversity
%aimport allel.stats
%aimport allel.plot
%aimport allel.opt.stats
%aimport allel.stats.sandbox

In [2]:
g = [[[0, 0], [0, 0], [1, 1], [1, 1]],
     [[0, 1], [0, 1], [0, 1], [0, 1]],
     [[0, 0], [0, 0], [0, 0], [0, 0]],
     [[0, 1], [1, 2], [1, 1], [2, 2]],
     [[0, 0], [1, 1], [0, 1], [-1, -1]]]
subpops = [[0, 1], [2, 3]]

In [8]:
a, b, c = allel.stats.sandbox.weir_cockerham_f_statistics(g, subpops)
a, b, c

DEBUG:allel.stats.sandbox:r: 2
DEBUG:allel.stats.sandbox:acs: (5, 3, 2), array([[[4, 0],
        [0, 4],
        [0, 0]],

       [[2, 2],
        [2, 2],
        [0, 0]],

       [[4, 4],
        [0, 0],
        [0, 0]],

       [[1, 0],
        [2, 2],
        [1, 2]],

       [[2, 1],
        [2, 1],
        [0, 0]]], dtype=int32)
DEBUG:allel.stats.sandbox:an: (5, 2), array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4],
       [4, 2]])
DEBUG:allel.stats.sandbox:n: (5, 2), array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 1]])
DEBUG:allel.stats.sandbox:n_total: (5,), array([4, 4, 4, 4, 3])
DEBUG:allel.stats.sandbox:ac: (5, 2), array([[0, 4],
       [2, 2],
       [0, 0],
       [2, 2],
       [2, 1]], dtype=int32)
DEBUG:allel.stats.sandbox:p: (5, 2), array([[ 0. ,  1. ],
       [ 0.5,  0.5],
       [ 0. ,  0. ],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])
DEBUG:allel.stats.sandbox:n_bar: (5,), array([ 2. ,  2. ,  2. ,  2. ,  1.5])
DEBUG:allel.stats.sandbox:

(array([ 0.5  ,  0.   ,  0.   , -0.125, -0.375]),
 array([ 0.        , -0.25      ,  0.        ,  0.125     ,  0.41666667]),
 array([ 0.        ,  0.5       ,  0.        ,  0.25      ,  0.16666667]))

In [9]:
a / (a + b + c)

array([ 1. ,  0. ,  nan, -0.5, -1.8])

In [11]:
a, b, c = allel.stats.weir_cockerham_variance_components(g, subpops)
a[:, 1], b[:, 1], c[:, 1]

DEBUG:allel.stats.diversity:r: 2
DEBUG:allel.stats.diversity:ac: (5, 3, 2), array([[[4, 0],
        [0, 4],
        [0, 0]],

       [[2, 2],
        [2, 2],
        [0, 0]],

       [[4, 4],
        [0, 0],
        [0, 0]],

       [[1, 0],
        [2, 2],
        [1, 2]],

       [[2, 1],
        [2, 1],
        [0, 0]]], dtype=int32)
DEBUG:allel.stats.diversity:an: (5, 2), array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4],
       [4, 2]])
DEBUG:allel.stats.diversity:n: (5, 2), array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 1]])
DEBUG:allel.stats.diversity:n_total: (5,), array([4, 4, 4, 4, 3])
DEBUG:allel.stats.diversity:n_bar: (5,), array([ 2. ,  2. ,  2. ,  2. ,  1.5])
DEBUG:allel.stats.diversity:n_C: (5,), array([ 2.        ,  2.        ,  2.        ,  2.        ,  1.33333333])
DEBUG:allel.stats.diversity:p: (5, 3, 2), array([[[ 1.  ,  0.  ],
        [ 0.  ,  1.  ],
        [ 0.  ,  0.  ]],

       [[ 0.5 ,  0.5 ],
        [ 0.5 ,  0.5 ],
        [

(array([ 0.5  ,  0.   ,  0.   , -0.125, -0.375]),
 array([ 0.        , -0.25      ,  0.        ,  0.125     ,  0.41666667]),
 array([ 0.        ,  0.5       ,  0.        ,  0.25      ,  0.16666667]))

In [12]:
a[:, 1] / (a[:, 1] + b[:, 1] + c[:, 1])

array([ 1. ,  0. ,  nan, -0.5, -1.8])

In [14]:
a[:, 2] / (a[:, 2] + b[:, 2] + c[:, 2])

array([ nan,  nan,  nan, -0.5,  nan])

In [13]:
np.sum(a, axis=1) / (np.sum(a, axis=1) + np.sum(b, axis=1) + np.sum(c, axis=1))

array([ 1. ,  0. ,  nan, -0.4, -1.8])

In [4]:
allel.stats.sandbox.naive_fst(g, subpops)

DEBUG:allel.stats.sandbox:r: 2
DEBUG:allel.stats.sandbox:acs: (4, 2, 2), array([[[4, 0],
        [0, 4]],

       [[2, 2],
        [2, 2]],

       [[4, 4],
        [0, 0]],

       [[2, 1],
        [2, 1]]], dtype=int32)
DEBUG:allel.stats.sandbox:an: (4, 2), array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 2]])
DEBUG:allel.stats.sandbox:n: (4, 2), array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 2]])
DEBUG:allel.stats.sandbox:p: (4, 2), array([[ 0. ,  1. ],
       [ 0.5,  0.5],
       [ 0. ,  0. ],
       [ 0.5,  0.5]])
DEBUG:allel.stats.sandbox:p_bar: (4,), array([ 0.5,  0.5,  0. ,  0.5])
DEBUG:allel.stats.sandbox:s_squared: (4,), array([ 0.25,  0.  ,  0.  ,  0.  ])


array([  1.,   0.,  nan,   0.])

In [5]:
g2 = [[[0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [1, 1], [1, 1], [1, 1]],
     [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]],
     [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]],
     [[0, 1], [1, 2], [0, 1], [1, 2], [1, 1], [2, 2], [1, 1], [2, 2]],
     [[0, 0], [1, 1], [0, 0], [1, 1], [0, 1], [-1, -1], [0, 1], [-1, -1]]]
subpops2 = [[0, 1, 2, 3], [4, 5, 6, 7]]

In [6]:
a, b, c = allel.stats.sandbox.weir_cockerham_f_statistics(g2, subpops2)
theta_hat = a / (a + b + c)
theta_hat

DEBUG:allel.stats.sandbox:r: 2
DEBUG:allel.stats.sandbox:acs: (5, 3, 2), array([[[8, 0],
        [0, 8],
        [0, 0]],

       [[4, 4],
        [4, 4],
        [0, 0]],

       [[8, 8],
        [0, 0],
        [0, 0]],

       [[2, 0],
        [4, 4],
        [2, 4]],

       [[4, 2],
        [4, 2],
        [0, 0]]], dtype=int32)
DEBUG:allel.stats.sandbox:an: (5, 2), array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8],
       [8, 4]])
DEBUG:allel.stats.sandbox:n: (5, 2), array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4],
       [4, 2]])
DEBUG:allel.stats.sandbox:n_total: (5,), array([8, 8, 8, 8, 6])
DEBUG:allel.stats.sandbox:ac: (5, 2), array([[0, 8],
       [4, 4],
       [0, 0],
       [4, 4],
       [4, 2]], dtype=int32)
DEBUG:allel.stats.sandbox:p: (5, 2), array([[ 0. ,  1. ],
       [ 0.5,  0.5],
       [ 0. ,  0. ],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])
DEBUG:allel.stats.sandbox:n_bar: (5,), array([ 4.,  4.,  4.,  4.,  3.])
DEBUG:allel.stats.sandbox:n_C (

array([ 1.        ,  0.        ,         nan, -0.16666667, -0.39130435])

In [7]:
allel.stats.sandbox.naive_fst(g2, subpops2)

DEBUG:allel.stats.sandbox:r: 2
DEBUG:allel.stats.sandbox:acs: (5, 3, 2), array([[[8, 0],
        [0, 8],
        [0, 0]],

       [[4, 4],
        [4, 4],
        [0, 0]],

       [[8, 8],
        [0, 0],
        [0, 0]],

       [[2, 0],
        [4, 4],
        [2, 4]],

       [[4, 2],
        [4, 2],
        [0, 0]]], dtype=int32)
DEBUG:allel.stats.sandbox:an: (5, 2), array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8],
       [8, 4]])
DEBUG:allel.stats.sandbox:n: (5, 2), array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8],
       [8, 4]])
DEBUG:allel.stats.sandbox:p: (5, 2), array([[ 0. ,  1. ],
       [ 0.5,  0.5],
       [ 0. ,  0. ],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])
DEBUG:allel.stats.sandbox:p_bar: (5,), array([ 0.5,  0.5,  0. ,  0.5,  0.5])
DEBUG:allel.stats.sandbox:s_squared: (5,), array([ 0.25,  0.  ,  0.  ,  0.  ,  0.  ])


array([  1.,   0.,  nan,   0.,   0.])

In [8]:
g3 = [[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [1, 1], [1, 1], [1, 1], [1, 1]],
     [[0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]],
     [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]],
     [[0, 1], [1, 2], [0, 1], [1, 2], [0, 1], [1, 2], [0, 1], [1, 2], [1, 1], [2, 2], [1, 1], [2, 2]],
     [[0, 0], [1, 1], [0, 0], [1, 1], [0, 0], [1, 1], [0, 0], [1, 1], [0, 1], [-1, -1], [0, 1], [-1, -1]]]
subpops3 = [list(range(8)), list(range(8, 12))]
subpops3

[[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11]]

In [9]:
a, b, c = allel.stats.sandbox.weir_cockerham_f_statistics(g3, subpops3)
theta_hat = a / (a + b + c)
theta_hat

DEBUG:allel.stats.sandbox:r: 2
DEBUG:allel.stats.sandbox:acs: (5, 3, 2), array([[[16,  0],
        [ 0,  8],
        [ 0,  0]],

       [[ 8,  4],
        [ 8,  4],
        [ 0,  0]],

       [[16,  8],
        [ 0,  0],
        [ 0,  0]],

       [[ 4,  0],
        [ 8,  4],
        [ 4,  4]],

       [[ 8,  2],
        [ 8,  2],
        [ 0,  0]]], dtype=int32)
DEBUG:allel.stats.sandbox:an: (5, 2), array([[16,  8],
       [16,  8],
       [16,  8],
       [16,  8],
       [16,  4]])
DEBUG:allel.stats.sandbox:n: (5, 2), array([[8, 4],
       [8, 4],
       [8, 4],
       [8, 4],
       [8, 2]])
DEBUG:allel.stats.sandbox:n_total: (5,), array([12, 12, 12, 12, 10])
DEBUG:allel.stats.sandbox:ac: (5, 2), array([[0, 8],
       [8, 4],
       [0, 0],
       [8, 4],
       [8, 2]], dtype=int32)
DEBUG:allel.stats.sandbox:p: (5, 2), array([[ 0. ,  1. ],
       [ 0.5,  0.5],
       [ 0. ,  0. ],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])
DEBUG:allel.stats.sandbox:n_bar: (5,), array([ 6.,  6.,  6

array([ 1.        ,  0.        ,         nan, -0.07563025, -0.35211268])

In [10]:
allel.stats.sandbox.naive_fst(g3, subpops3)

DEBUG:allel.stats.sandbox:r: 2
DEBUG:allel.stats.sandbox:acs: (5, 3, 2), array([[[16,  0],
        [ 0,  8],
        [ 0,  0]],

       [[ 8,  4],
        [ 8,  4],
        [ 0,  0]],

       [[16,  8],
        [ 0,  0],
        [ 0,  0]],

       [[ 4,  0],
        [ 8,  4],
        [ 4,  4]],

       [[ 8,  2],
        [ 8,  2],
        [ 0,  0]]], dtype=int32)
DEBUG:allel.stats.sandbox:an: (5, 2), array([[16,  8],
       [16,  8],
       [16,  8],
       [16,  8],
       [16,  4]])
DEBUG:allel.stats.sandbox:n: (5, 2), array([[16,  8],
       [16,  8],
       [16,  8],
       [16,  8],
       [16,  4]])
DEBUG:allel.stats.sandbox:p: (5, 2), array([[ 0. ,  1. ],
       [ 0.5,  0.5],
       [ 0. ,  0. ],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])
DEBUG:allel.stats.sandbox:p_bar: (5,), array([ 0.5,  0.5,  0. ,  0.5,  0.5])
DEBUG:allel.stats.sandbox:s_squared: (5,), array([ 0.25,  0.  ,  0.  ,  0.  ,  0.  ])


array([  1.,   0.,  nan,   0.,   0.])