In [1]:
import sys
sys.path.insert(0, '../')
import numpy as np
%reload_ext autoreload
%autoreload 1
%aimport allel
%aimport allel.model
%aimport allel.model.ndarray
%aimport allel.model.chunked
allel.__version__

'0.20.2'

In [2]:
# setup an array of genotype calls
shape = n_variants, n_samples, ploidy = 50000, 1000, 2
data = np.zeros(shape, dtype='i1')
# simulate some mutations
n_alleles = n_variants * n_samples * ploidy
idx = np.random.randint(0, (n_alleles//2)-1, size=n_alleles//20)
data[:, :, 1].reshape((-1))[idx] = 1
data[:, :, 0].reshape((-1))[idx[:n_alleles//200]] = 1
g = allel.GenotypeArray(data, copy=False)

In [3]:
g

GenotypeArray((50000, 1000, 2), dtype=int8)
[[[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 ..., 
 [[0 1]
  [0 0]
  [0 0]
  ..., 
  [0 1]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  ..., 
  [0 0]
  [0 0]
  [0 0]]]

In [4]:
g.take([0, 1, 2], axis=1)

GenotypeArray((50000, 3, 2), dtype=int8)
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 ..., 
 [[0 1]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]

In [5]:
h = g.to_haplotypes()
h

HaplotypeArray((50000, 2000), dtype=int8)
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 1 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]

In [6]:
h.take([0, 1, 2], axis=1)

HaplotypeArray((50000, 3), dtype=int8)
[[0 0 0]
 [0 0 0]
 [0 0 0]
 ..., 
 [0 1 0]
 [0 0 0]
 [0 0 0]]

In [7]:
gc = allel.GenotypeChunkedArray(g).copy()
gc

GenotypeChunkedArray((50000, 1000, 2), int8, nbytes=95.4M, cbytes=16.0M, cratio=6.0, cname=blosclz, clevel=5, shuffle=True, chunks=(262, 1000, 2), data=bcolz.carray_ext.carray)

In [8]:
gc.take([0, 1, 2], axis=1)

GenotypeChunkedArray((50000, 3, 2), int8, nbytes=293.0K, cbytes=297.8K, cratio=1.0, cname=blosclz, clevel=5, shuffle=True, chunks=(43690, 3, 2), data=bcolz.carray_ext.carray)

In [9]:
hc = gc.to_haplotypes()
hc

HaplotypeChunkedArray((50000, 2000), int8, nbytes=95.4M, cbytes=16.0M, cratio=6.0, cname=blosclz, clevel=5, shuffle=True, chunks=(262, 2000), data=bcolz.carray_ext.carray)

In [10]:
hc.take([0, 1, 2], axis=1)

HaplotypeChunkedArray((50000, 3), int8, nbytes=146.5K, cbytes=256.0K, cratio=0.6, cname=blosclz, clevel=5, shuffle=True, chunks=(87381, 3), data=bcolz.carray_ext.carray)

In [11]:
ac = g.count_alleles()
ac

AlleleCountsArray((50000, 2), dtype=int32)
[[1911   89]
 [1895  105]
 [1896  104]
 ..., 
 [1908   92]
 [1887  113]
 [1904   96]]

In [12]:
acc = gc.count_alleles()
acc

AlleleCountsChunkedArray((50000, 2), int32, nbytes=390.6K, cbytes=321.3K, cratio=1.2, cname=blosclz, clevel=5, shuffle=True, chunks=(32768, 2), data=bcolz.carray_ext.carray)

In [13]:
gc.is_called()

carray((50000, 1000), bool)
  nbytes: 47.68 MB; cbytes: 743.19 KB; ratio: 65.70
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[[ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 ..., 
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]]

In [14]:
gc.to_n_alt()

ChunkedArray((50000, 1000), int8, nbytes=47.7M, cbytes=13.0M, cratio=3.7, cname=blosclz, clevel=5, shuffle=True, chunks=(524, 1000), data=bcolz.carray_ext.carray)

In [15]:
pos = np.unique(np.random.randint(0, 1000000, size=50000))
pos

array([     9,     28,     30, ..., 999946, 999958, 999960])

In [16]:
ref = np.random.choice([b'A', b'C', b'T', b'G'], size=pos.shape[0])
ref

array([b'A', b'T', b'A', ..., b'G', b'G', b'A'], 
      dtype='|S1')

In [17]:
alt = np.random.choice([b'A', b'C', b'T', b'G'], size=pos.shape[0])
alt

array([b'G', b'A', b'A', ..., b'A', b'T', b'A'], 
      dtype='|S1')

In [18]:
ra = np.rec.fromarrays([pos, ref, alt], names=['POS', 'REF', 'ALT'])
vtbl = allel.VariantTable(ra)
vtbl

VariantTable((48752,), dtype=(numpy.record, [('POS', '<i8'), ('REF', 'S1'), ('ALT', 'S1')]))
[(9, b'A', b'G') (28, b'T', b'A') (30, b'A', b'A') ...,
 (999946, b'G', b'A') (999958, b'G', b'T') (999960, b'A', b'A')]

In [19]:
vctbl = allel.VariantChunkedTable(vtbl).copy()
vctbl

VariantChunkedTable(48752, nbytes=476.1K, cbytes=557.2K, cratio=0.9, data=bcolz.ctable.ctable)

In [20]:
vtbl[:5].display(10)

VariantTable((5,), dtype=(numpy.record, [('POS', '<i8'), ('REF', 'S1'), ('ALT', 'S1')])) 
 
 
 POS 
 REF 
 ALT 
 
 
 
 
 9 
 b'A' 
 b'G' 
 
 
 28 
 b'T' 
 b'A' 
 
 
 30 
 b'A' 
 b'A' 
 
 
 43 
 b'C' 
 b'T' 
 
 
 53 
 b'G' 
 b'A'

In [21]:
vtbl[:5].display(None)

VariantTable((5,), dtype=(numpy.record, [('POS', '<i8'), ('REF', 'S1'), ('ALT', 'S1')])) 
 
 
 POS 
 REF 
 ALT 
 
 
 
 
 9 
 b'A' 
 b'G' 
 
 
 28 
 b'T' 
 b'A' 
 
 
 30 
 b'A' 
 b'A' 
 
 
 43 
 b'C' 
 b'T' 
 
 
 53 
 b'G' 
 b'A'

In [22]:
vtbl[:5].displayall()

VariantTable((5,), dtype=(numpy.record, [('POS', '<i8'), ('REF', 'S1'), ('ALT', 'S1')])) 
 
 
 POS 
 REF 
 ALT 
 
 
 
 
 9 
 b'A' 
 b'G' 
 
 
 28 
 b'T' 
 b'A' 
 
 
 30 
 b'A' 
 b'A' 
 
 
 43 
 b'C' 
 b'T' 
 
 
 53 
 b'G' 
 b'A'

In [23]:
vctbl.take(list(range(5))).display(10)

VariantChunkedTable(5, nbytes=50, cbytes=48.0K, cratio=0.0, data=bcolz.ctable.ctable) 
 
 
 POS 
 REF 
 ALT 
 
 
 
 
 9 
 b'A' 
 b'G' 
 
 
 28 
 b'T' 
 b'A' 
 
 
 30 
 b'A' 
 b'A' 
 
 
 43 
 b'C' 
 b'T' 
 
 
 53 
 b'G' 
 b'A'

In [24]:
vctbl.take(list(range(5))).display(None)

VariantChunkedTable(5, nbytes=50, cbytes=48.0K, cratio=0.0, data=bcolz.ctable.ctable) 
 
 
 POS 
 REF 
 ALT 
 
 
 
 
 9 
 b'A' 
 b'G' 
 
 
 28 
 b'T' 
 b'A' 
 
 
 30 
 b'A' 
 b'A' 
 
 
 43 
 b'C' 
 b'T' 
 
 
 53 
 b'G' 
 b'A'

In [25]:
vctbl.take(list(range(5))).displayall()

VariantChunkedTable(5, nbytes=50, cbytes=48.0K, cratio=0.0, data=bcolz.ctable.ctable) 
 
 
 POS 
 REF 
 ALT 
 
 
 
 
 9 
 b'A' 
 b'G' 
 
 
 28 
 b'T' 
 b'A' 
 
 
 30 
 b'A' 
 b'A' 
 
 
 43 
 b'C' 
 b'T' 
 
 
 53 
 b'G' 
 b'A'